import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthState from "@/components/auth/auth-state";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import LeftSection from "@/components/sections/left/left";
import RightSection from "@/components/sections/right/right";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(poppins.className, "bg-[#f4f5f8] h-dvh overflow-hidden")}
      >
        <main className="h-full flex flex-col">
          <Header />
          <div className="h-full flex shrink-0 flex-1 gap-6 p-6">
            <LeftSection />
            {children}
            <RightSection />
          </div>
        </main>
        <AuthState />
        <Toaster />
      </body>
    </html>
  );
}
