import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthState from "@/components/auth/auth-state";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "bg-[#F6F6F6]")}>
        {children}
        <AuthState />
        <Toaster />
      </body>
    </html>
  );
}
